on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number'
        required: true
permissions:
  issues: write
jobs:
  workflow_test:
    runs-on: ubuntu-latest
    steps:
      - name: rewritable-issue-comment
        uses: nakamuloud/actions-rewritable-comment@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BODY: 'Hello World'
          ISSUE_NUMBER: ${{ github.event.inputs.issue_number }}
