name: rewritable-issue-comment
on:
  pull_request:
permissions:
  issues: write
  pull-requests: write
jobs:
  workflow_test:
    runs-on: ubuntu-latest
    steps:
      - name: rewritable-issue-comment
        uses: nakamuloud/actions-rewritable-comment@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALUE: 'Hello World'
