on:
  pull_request:
    branches:
      - main
permissions:
  issues: write
jobs:
  workflow_test:
    runs-on: ubuntu-latest
    steps:
      - name: rewritable-issue-comment
        uses: nakamuloud/actions-rewritable-comment@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALUE: 'Hello World'
