on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number'
        required: true
  pull_request:
    branches:
      - main
permissions:
  issues: write
jobs:
  workflow_test:
    runs-on: ubuntu-latest
    steps:
      - name: rewritable-issue-comment
        uses: nakamuloud/actions-rewritable-comment@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALUE: 'Hello World'
