on:
  workflow_dispatch:
permissions:
  issues: write
jobs:
  workflow_test:
    runs-on: ubuntu-latest
    steps:
      - name: rewritable-issue-comment
        uses: nakamuloud/actions-rewritable-comment@main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
